// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_block.proto

package ai.sapper.hcdc.common.model;

/**
 * Protobuf type {@code ai_sapper_hcdc_common_model.DFSRenameFile}
 */
public  final class DFSRenameFile extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ai_sapper_hcdc_common_model.DFSRenameFile)
    DFSRenameFileOrBuilder {
  // Use DFSRenameFile.newBuilder() to construct.
  private DFSRenameFile(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DFSRenameFile() {
    length_ = 0L;
    opts_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private DFSRenameFile(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            ai.sapper.hcdc.common.model.DFSTransaction.Builder subBuilder = null;
            if (transaction_ != null) {
              subBuilder = transaction_.toBuilder();
            }
            transaction_ = input.readMessage(ai.sapper.hcdc.common.model.DFSTransaction.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(transaction_);
              transaction_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            ai.sapper.hcdc.common.model.DFSFile.Builder subBuilder = null;
            if (srcFile_ != null) {
              subBuilder = srcFile_.toBuilder();
            }
            srcFile_ = input.readMessage(ai.sapper.hcdc.common.model.DFSFile.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(srcFile_);
              srcFile_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            ai.sapper.hcdc.common.model.DFSFile.Builder subBuilder = null;
            if (destFile_ != null) {
              subBuilder = destFile_.toBuilder();
            }
            destFile_ = input.readMessage(ai.sapper.hcdc.common.model.DFSFile.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(destFile_);
              destFile_ = subBuilder.buildPartial();
            }

            break;
          }
          case 32: {

            length_ = input.readUInt64();
            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            opts_ = rawValue;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ai.sapper.hcdc.common.model.HcdcDFSBlockProtos.internal_static_ai_sapper_hcdc_common_model_DFSRenameFile_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ai.sapper.hcdc.common.model.HcdcDFSBlockProtos.internal_static_ai_sapper_hcdc_common_model_DFSRenameFile_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ai.sapper.hcdc.common.model.DFSRenameFile.class, ai.sapper.hcdc.common.model.DFSRenameFile.Builder.class);
  }

  /**
   * Protobuf enum {@code ai_sapper_hcdc_common_model.DFSRenameFile.RenameOpts}
   */
  public enum RenameOpts
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NONE = 0;</code>
     */
    NONE(0),
    /**
     * <code>OVERWRITE = 1;</code>
     */
    OVERWRITE(1),
    /**
     * <code>TO_TRASH = 2;</code>
     */
    TO_TRASH(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NONE = 0;</code>
     */
    public static final int NONE_VALUE = 0;
    /**
     * <code>OVERWRITE = 1;</code>
     */
    public static final int OVERWRITE_VALUE = 1;
    /**
     * <code>TO_TRASH = 2;</code>
     */
    public static final int TO_TRASH_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RenameOpts valueOf(int value) {
      return forNumber(value);
    }

    public static RenameOpts forNumber(int value) {
      switch (value) {
        case 0: return NONE;
        case 1: return OVERWRITE;
        case 2: return TO_TRASH;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RenameOpts>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RenameOpts> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RenameOpts>() {
            public RenameOpts findValueByNumber(int number) {
              return RenameOpts.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ai.sapper.hcdc.common.model.DFSRenameFile.getDescriptor().getEnumTypes().get(0);
    }

    private static final RenameOpts[] VALUES = values();

    public static RenameOpts valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RenameOpts(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ai_sapper_hcdc_common_model.DFSRenameFile.RenameOpts)
  }

  public static final int TRANSACTION_FIELD_NUMBER = 1;
  private ai.sapper.hcdc.common.model.DFSTransaction transaction_;
  /**
   * <code>optional .ai_sapper_hcdc_common_model.DFSTransaction transaction = 1;</code>
   */
  public boolean hasTransaction() {
    return transaction_ != null;
  }
  /**
   * <code>optional .ai_sapper_hcdc_common_model.DFSTransaction transaction = 1;</code>
   */
  public ai.sapper.hcdc.common.model.DFSTransaction getTransaction() {
    return transaction_ == null ? ai.sapper.hcdc.common.model.DFSTransaction.getDefaultInstance() : transaction_;
  }
  /**
   * <code>optional .ai_sapper_hcdc_common_model.DFSTransaction transaction = 1;</code>
   */
  public ai.sapper.hcdc.common.model.DFSTransactionOrBuilder getTransactionOrBuilder() {
    return getTransaction();
  }

  public static final int SRCFILE_FIELD_NUMBER = 2;
  private ai.sapper.hcdc.common.model.DFSFile srcFile_;
  /**
   * <code>optional .ai_sapper_hcdc_common_model.DFSFile srcFile = 2;</code>
   */
  public boolean hasSrcFile() {
    return srcFile_ != null;
  }
  /**
   * <code>optional .ai_sapper_hcdc_common_model.DFSFile srcFile = 2;</code>
   */
  public ai.sapper.hcdc.common.model.DFSFile getSrcFile() {
    return srcFile_ == null ? ai.sapper.hcdc.common.model.DFSFile.getDefaultInstance() : srcFile_;
  }
  /**
   * <code>optional .ai_sapper_hcdc_common_model.DFSFile srcFile = 2;</code>
   */
  public ai.sapper.hcdc.common.model.DFSFileOrBuilder getSrcFileOrBuilder() {
    return getSrcFile();
  }

  public static final int DESTFILE_FIELD_NUMBER = 3;
  private ai.sapper.hcdc.common.model.DFSFile destFile_;
  /**
   * <code>optional .ai_sapper_hcdc_common_model.DFSFile destFile = 3;</code>
   */
  public boolean hasDestFile() {
    return destFile_ != null;
  }
  /**
   * <code>optional .ai_sapper_hcdc_common_model.DFSFile destFile = 3;</code>
   */
  public ai.sapper.hcdc.common.model.DFSFile getDestFile() {
    return destFile_ == null ? ai.sapper.hcdc.common.model.DFSFile.getDefaultInstance() : destFile_;
  }
  /**
   * <code>optional .ai_sapper_hcdc_common_model.DFSFile destFile = 3;</code>
   */
  public ai.sapper.hcdc.common.model.DFSFileOrBuilder getDestFileOrBuilder() {
    return getDestFile();
  }

  public static final int LENGTH_FIELD_NUMBER = 4;
  private long length_;
  /**
   * <code>optional uint64 length = 4;</code>
   */
  public long getLength() {
    return length_;
  }

  public static final int OPTS_FIELD_NUMBER = 5;
  private int opts_;
  /**
   * <code>optional .ai_sapper_hcdc_common_model.DFSRenameFile.RenameOpts opts = 5;</code>
   */
  public int getOptsValue() {
    return opts_;
  }
  /**
   * <code>optional .ai_sapper_hcdc_common_model.DFSRenameFile.RenameOpts opts = 5;</code>
   */
  public ai.sapper.hcdc.common.model.DFSRenameFile.RenameOpts getOpts() {
    ai.sapper.hcdc.common.model.DFSRenameFile.RenameOpts result = ai.sapper.hcdc.common.model.DFSRenameFile.RenameOpts.valueOf(opts_);
    return result == null ? ai.sapper.hcdc.common.model.DFSRenameFile.RenameOpts.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (transaction_ != null) {
      output.writeMessage(1, getTransaction());
    }
    if (srcFile_ != null) {
      output.writeMessage(2, getSrcFile());
    }
    if (destFile_ != null) {
      output.writeMessage(3, getDestFile());
    }
    if (length_ != 0L) {
      output.writeUInt64(4, length_);
    }
    if (opts_ != ai.sapper.hcdc.common.model.DFSRenameFile.RenameOpts.NONE.getNumber()) {
      output.writeEnum(5, opts_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (transaction_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTransaction());
    }
    if (srcFile_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getSrcFile());
    }
    if (destFile_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getDestFile());
    }
    if (length_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, length_);
    }
    if (opts_ != ai.sapper.hcdc.common.model.DFSRenameFile.RenameOpts.NONE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, opts_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ai.sapper.hcdc.common.model.DFSRenameFile)) {
      return super.equals(obj);
    }
    ai.sapper.hcdc.common.model.DFSRenameFile other = (ai.sapper.hcdc.common.model.DFSRenameFile) obj;

    boolean result = true;
    result = result && (hasTransaction() == other.hasTransaction());
    if (hasTransaction()) {
      result = result && getTransaction()
          .equals(other.getTransaction());
    }
    result = result && (hasSrcFile() == other.hasSrcFile());
    if (hasSrcFile()) {
      result = result && getSrcFile()
          .equals(other.getSrcFile());
    }
    result = result && (hasDestFile() == other.hasDestFile());
    if (hasDestFile()) {
      result = result && getDestFile()
          .equals(other.getDestFile());
    }
    result = result && (getLength()
        == other.getLength());
    result = result && opts_ == other.opts_;
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasTransaction()) {
      hash = (37 * hash) + TRANSACTION_FIELD_NUMBER;
      hash = (53 * hash) + getTransaction().hashCode();
    }
    if (hasSrcFile()) {
      hash = (37 * hash) + SRCFILE_FIELD_NUMBER;
      hash = (53 * hash) + getSrcFile().hashCode();
    }
    if (hasDestFile()) {
      hash = (37 * hash) + DESTFILE_FIELD_NUMBER;
      hash = (53 * hash) + getDestFile().hashCode();
    }
    hash = (37 * hash) + LENGTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLength());
    hash = (37 * hash) + OPTS_FIELD_NUMBER;
    hash = (53 * hash) + opts_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ai.sapper.hcdc.common.model.DFSRenameFile parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.sapper.hcdc.common.model.DFSRenameFile parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.sapper.hcdc.common.model.DFSRenameFile parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.sapper.hcdc.common.model.DFSRenameFile parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.sapper.hcdc.common.model.DFSRenameFile parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.sapper.hcdc.common.model.DFSRenameFile parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.sapper.hcdc.common.model.DFSRenameFile parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ai.sapper.hcdc.common.model.DFSRenameFile parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.sapper.hcdc.common.model.DFSRenameFile parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.sapper.hcdc.common.model.DFSRenameFile parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ai.sapper.hcdc.common.model.DFSRenameFile prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ai_sapper_hcdc_common_model.DFSRenameFile}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ai_sapper_hcdc_common_model.DFSRenameFile)
      ai.sapper.hcdc.common.model.DFSRenameFileOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ai.sapper.hcdc.common.model.HcdcDFSBlockProtos.internal_static_ai_sapper_hcdc_common_model_DFSRenameFile_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ai.sapper.hcdc.common.model.HcdcDFSBlockProtos.internal_static_ai_sapper_hcdc_common_model_DFSRenameFile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ai.sapper.hcdc.common.model.DFSRenameFile.class, ai.sapper.hcdc.common.model.DFSRenameFile.Builder.class);
    }

    // Construct using ai.sapper.hcdc.common.model.DFSRenameFile.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (transactionBuilder_ == null) {
        transaction_ = null;
      } else {
        transaction_ = null;
        transactionBuilder_ = null;
      }
      if (srcFileBuilder_ == null) {
        srcFile_ = null;
      } else {
        srcFile_ = null;
        srcFileBuilder_ = null;
      }
      if (destFileBuilder_ == null) {
        destFile_ = null;
      } else {
        destFile_ = null;
        destFileBuilder_ = null;
      }
      length_ = 0L;

      opts_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ai.sapper.hcdc.common.model.HcdcDFSBlockProtos.internal_static_ai_sapper_hcdc_common_model_DFSRenameFile_descriptor;
    }

    public ai.sapper.hcdc.common.model.DFSRenameFile getDefaultInstanceForType() {
      return ai.sapper.hcdc.common.model.DFSRenameFile.getDefaultInstance();
    }

    public ai.sapper.hcdc.common.model.DFSRenameFile build() {
      ai.sapper.hcdc.common.model.DFSRenameFile result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public ai.sapper.hcdc.common.model.DFSRenameFile buildPartial() {
      ai.sapper.hcdc.common.model.DFSRenameFile result = new ai.sapper.hcdc.common.model.DFSRenameFile(this);
      if (transactionBuilder_ == null) {
        result.transaction_ = transaction_;
      } else {
        result.transaction_ = transactionBuilder_.build();
      }
      if (srcFileBuilder_ == null) {
        result.srcFile_ = srcFile_;
      } else {
        result.srcFile_ = srcFileBuilder_.build();
      }
      if (destFileBuilder_ == null) {
        result.destFile_ = destFile_;
      } else {
        result.destFile_ = destFileBuilder_.build();
      }
      result.length_ = length_;
      result.opts_ = opts_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ai.sapper.hcdc.common.model.DFSRenameFile) {
        return mergeFrom((ai.sapper.hcdc.common.model.DFSRenameFile)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ai.sapper.hcdc.common.model.DFSRenameFile other) {
      if (other == ai.sapper.hcdc.common.model.DFSRenameFile.getDefaultInstance()) return this;
      if (other.hasTransaction()) {
        mergeTransaction(other.getTransaction());
      }
      if (other.hasSrcFile()) {
        mergeSrcFile(other.getSrcFile());
      }
      if (other.hasDestFile()) {
        mergeDestFile(other.getDestFile());
      }
      if (other.getLength() != 0L) {
        setLength(other.getLength());
      }
      if (other.opts_ != 0) {
        setOptsValue(other.getOptsValue());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ai.sapper.hcdc.common.model.DFSRenameFile parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ai.sapper.hcdc.common.model.DFSRenameFile) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private ai.sapper.hcdc.common.model.DFSTransaction transaction_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        ai.sapper.hcdc.common.model.DFSTransaction, ai.sapper.hcdc.common.model.DFSTransaction.Builder, ai.sapper.hcdc.common.model.DFSTransactionOrBuilder> transactionBuilder_;
    /**
     * <code>optional .ai_sapper_hcdc_common_model.DFSTransaction transaction = 1;</code>
     */
    public boolean hasTransaction() {
      return transactionBuilder_ != null || transaction_ != null;
    }
    /**
     * <code>optional .ai_sapper_hcdc_common_model.DFSTransaction transaction = 1;</code>
     */
    public ai.sapper.hcdc.common.model.DFSTransaction getTransaction() {
      if (transactionBuilder_ == null) {
        return transaction_ == null ? ai.sapper.hcdc.common.model.DFSTransaction.getDefaultInstance() : transaction_;
      } else {
        return transactionBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .ai_sapper_hcdc_common_model.DFSTransaction transaction = 1;</code>
     */
    public Builder setTransaction(ai.sapper.hcdc.common.model.DFSTransaction value) {
      if (transactionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        transaction_ = value;
        onChanged();
      } else {
        transactionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .ai_sapper_hcdc_common_model.DFSTransaction transaction = 1;</code>
     */
    public Builder setTransaction(
        ai.sapper.hcdc.common.model.DFSTransaction.Builder builderForValue) {
      if (transactionBuilder_ == null) {
        transaction_ = builderForValue.build();
        onChanged();
      } else {
        transactionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .ai_sapper_hcdc_common_model.DFSTransaction transaction = 1;</code>
     */
    public Builder mergeTransaction(ai.sapper.hcdc.common.model.DFSTransaction value) {
      if (transactionBuilder_ == null) {
        if (transaction_ != null) {
          transaction_ =
            ai.sapper.hcdc.common.model.DFSTransaction.newBuilder(transaction_).mergeFrom(value).buildPartial();
        } else {
          transaction_ = value;
        }
        onChanged();
      } else {
        transactionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .ai_sapper_hcdc_common_model.DFSTransaction transaction = 1;</code>
     */
    public Builder clearTransaction() {
      if (transactionBuilder_ == null) {
        transaction_ = null;
        onChanged();
      } else {
        transaction_ = null;
        transactionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .ai_sapper_hcdc_common_model.DFSTransaction transaction = 1;</code>
     */
    public ai.sapper.hcdc.common.model.DFSTransaction.Builder getTransactionBuilder() {
      
      onChanged();
      return getTransactionFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .ai_sapper_hcdc_common_model.DFSTransaction transaction = 1;</code>
     */
    public ai.sapper.hcdc.common.model.DFSTransactionOrBuilder getTransactionOrBuilder() {
      if (transactionBuilder_ != null) {
        return transactionBuilder_.getMessageOrBuilder();
      } else {
        return transaction_ == null ?
            ai.sapper.hcdc.common.model.DFSTransaction.getDefaultInstance() : transaction_;
      }
    }
    /**
     * <code>optional .ai_sapper_hcdc_common_model.DFSTransaction transaction = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ai.sapper.hcdc.common.model.DFSTransaction, ai.sapper.hcdc.common.model.DFSTransaction.Builder, ai.sapper.hcdc.common.model.DFSTransactionOrBuilder> 
        getTransactionFieldBuilder() {
      if (transactionBuilder_ == null) {
        transactionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ai.sapper.hcdc.common.model.DFSTransaction, ai.sapper.hcdc.common.model.DFSTransaction.Builder, ai.sapper.hcdc.common.model.DFSTransactionOrBuilder>(
                getTransaction(),
                getParentForChildren(),
                isClean());
        transaction_ = null;
      }
      return transactionBuilder_;
    }

    private ai.sapper.hcdc.common.model.DFSFile srcFile_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        ai.sapper.hcdc.common.model.DFSFile, ai.sapper.hcdc.common.model.DFSFile.Builder, ai.sapper.hcdc.common.model.DFSFileOrBuilder> srcFileBuilder_;
    /**
     * <code>optional .ai_sapper_hcdc_common_model.DFSFile srcFile = 2;</code>
     */
    public boolean hasSrcFile() {
      return srcFileBuilder_ != null || srcFile_ != null;
    }
    /**
     * <code>optional .ai_sapper_hcdc_common_model.DFSFile srcFile = 2;</code>
     */
    public ai.sapper.hcdc.common.model.DFSFile getSrcFile() {
      if (srcFileBuilder_ == null) {
        return srcFile_ == null ? ai.sapper.hcdc.common.model.DFSFile.getDefaultInstance() : srcFile_;
      } else {
        return srcFileBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .ai_sapper_hcdc_common_model.DFSFile srcFile = 2;</code>
     */
    public Builder setSrcFile(ai.sapper.hcdc.common.model.DFSFile value) {
      if (srcFileBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        srcFile_ = value;
        onChanged();
      } else {
        srcFileBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .ai_sapper_hcdc_common_model.DFSFile srcFile = 2;</code>
     */
    public Builder setSrcFile(
        ai.sapper.hcdc.common.model.DFSFile.Builder builderForValue) {
      if (srcFileBuilder_ == null) {
        srcFile_ = builderForValue.build();
        onChanged();
      } else {
        srcFileBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .ai_sapper_hcdc_common_model.DFSFile srcFile = 2;</code>
     */
    public Builder mergeSrcFile(ai.sapper.hcdc.common.model.DFSFile value) {
      if (srcFileBuilder_ == null) {
        if (srcFile_ != null) {
          srcFile_ =
            ai.sapper.hcdc.common.model.DFSFile.newBuilder(srcFile_).mergeFrom(value).buildPartial();
        } else {
          srcFile_ = value;
        }
        onChanged();
      } else {
        srcFileBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .ai_sapper_hcdc_common_model.DFSFile srcFile = 2;</code>
     */
    public Builder clearSrcFile() {
      if (srcFileBuilder_ == null) {
        srcFile_ = null;
        onChanged();
      } else {
        srcFile_ = null;
        srcFileBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .ai_sapper_hcdc_common_model.DFSFile srcFile = 2;</code>
     */
    public ai.sapper.hcdc.common.model.DFSFile.Builder getSrcFileBuilder() {
      
      onChanged();
      return getSrcFileFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .ai_sapper_hcdc_common_model.DFSFile srcFile = 2;</code>
     */
    public ai.sapper.hcdc.common.model.DFSFileOrBuilder getSrcFileOrBuilder() {
      if (srcFileBuilder_ != null) {
        return srcFileBuilder_.getMessageOrBuilder();
      } else {
        return srcFile_ == null ?
            ai.sapper.hcdc.common.model.DFSFile.getDefaultInstance() : srcFile_;
      }
    }
    /**
     * <code>optional .ai_sapper_hcdc_common_model.DFSFile srcFile = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ai.sapper.hcdc.common.model.DFSFile, ai.sapper.hcdc.common.model.DFSFile.Builder, ai.sapper.hcdc.common.model.DFSFileOrBuilder> 
        getSrcFileFieldBuilder() {
      if (srcFileBuilder_ == null) {
        srcFileBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ai.sapper.hcdc.common.model.DFSFile, ai.sapper.hcdc.common.model.DFSFile.Builder, ai.sapper.hcdc.common.model.DFSFileOrBuilder>(
                getSrcFile(),
                getParentForChildren(),
                isClean());
        srcFile_ = null;
      }
      return srcFileBuilder_;
    }

    private ai.sapper.hcdc.common.model.DFSFile destFile_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        ai.sapper.hcdc.common.model.DFSFile, ai.sapper.hcdc.common.model.DFSFile.Builder, ai.sapper.hcdc.common.model.DFSFileOrBuilder> destFileBuilder_;
    /**
     * <code>optional .ai_sapper_hcdc_common_model.DFSFile destFile = 3;</code>
     */
    public boolean hasDestFile() {
      return destFileBuilder_ != null || destFile_ != null;
    }
    /**
     * <code>optional .ai_sapper_hcdc_common_model.DFSFile destFile = 3;</code>
     */
    public ai.sapper.hcdc.common.model.DFSFile getDestFile() {
      if (destFileBuilder_ == null) {
        return destFile_ == null ? ai.sapper.hcdc.common.model.DFSFile.getDefaultInstance() : destFile_;
      } else {
        return destFileBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .ai_sapper_hcdc_common_model.DFSFile destFile = 3;</code>
     */
    public Builder setDestFile(ai.sapper.hcdc.common.model.DFSFile value) {
      if (destFileBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        destFile_ = value;
        onChanged();
      } else {
        destFileBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .ai_sapper_hcdc_common_model.DFSFile destFile = 3;</code>
     */
    public Builder setDestFile(
        ai.sapper.hcdc.common.model.DFSFile.Builder builderForValue) {
      if (destFileBuilder_ == null) {
        destFile_ = builderForValue.build();
        onChanged();
      } else {
        destFileBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .ai_sapper_hcdc_common_model.DFSFile destFile = 3;</code>
     */
    public Builder mergeDestFile(ai.sapper.hcdc.common.model.DFSFile value) {
      if (destFileBuilder_ == null) {
        if (destFile_ != null) {
          destFile_ =
            ai.sapper.hcdc.common.model.DFSFile.newBuilder(destFile_).mergeFrom(value).buildPartial();
        } else {
          destFile_ = value;
        }
        onChanged();
      } else {
        destFileBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .ai_sapper_hcdc_common_model.DFSFile destFile = 3;</code>
     */
    public Builder clearDestFile() {
      if (destFileBuilder_ == null) {
        destFile_ = null;
        onChanged();
      } else {
        destFile_ = null;
        destFileBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .ai_sapper_hcdc_common_model.DFSFile destFile = 3;</code>
     */
    public ai.sapper.hcdc.common.model.DFSFile.Builder getDestFileBuilder() {
      
      onChanged();
      return getDestFileFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .ai_sapper_hcdc_common_model.DFSFile destFile = 3;</code>
     */
    public ai.sapper.hcdc.common.model.DFSFileOrBuilder getDestFileOrBuilder() {
      if (destFileBuilder_ != null) {
        return destFileBuilder_.getMessageOrBuilder();
      } else {
        return destFile_ == null ?
            ai.sapper.hcdc.common.model.DFSFile.getDefaultInstance() : destFile_;
      }
    }
    /**
     * <code>optional .ai_sapper_hcdc_common_model.DFSFile destFile = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ai.sapper.hcdc.common.model.DFSFile, ai.sapper.hcdc.common.model.DFSFile.Builder, ai.sapper.hcdc.common.model.DFSFileOrBuilder> 
        getDestFileFieldBuilder() {
      if (destFileBuilder_ == null) {
        destFileBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ai.sapper.hcdc.common.model.DFSFile, ai.sapper.hcdc.common.model.DFSFile.Builder, ai.sapper.hcdc.common.model.DFSFileOrBuilder>(
                getDestFile(),
                getParentForChildren(),
                isClean());
        destFile_ = null;
      }
      return destFileBuilder_;
    }

    private long length_ ;
    /**
     * <code>optional uint64 length = 4;</code>
     */
    public long getLength() {
      return length_;
    }
    /**
     * <code>optional uint64 length = 4;</code>
     */
    public Builder setLength(long value) {
      
      length_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 length = 4;</code>
     */
    public Builder clearLength() {
      
      length_ = 0L;
      onChanged();
      return this;
    }

    private int opts_ = 0;
    /**
     * <code>optional .ai_sapper_hcdc_common_model.DFSRenameFile.RenameOpts opts = 5;</code>
     */
    public int getOptsValue() {
      return opts_;
    }
    /**
     * <code>optional .ai_sapper_hcdc_common_model.DFSRenameFile.RenameOpts opts = 5;</code>
     */
    public Builder setOptsValue(int value) {
      opts_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .ai_sapper_hcdc_common_model.DFSRenameFile.RenameOpts opts = 5;</code>
     */
    public ai.sapper.hcdc.common.model.DFSRenameFile.RenameOpts getOpts() {
      ai.sapper.hcdc.common.model.DFSRenameFile.RenameOpts result = ai.sapper.hcdc.common.model.DFSRenameFile.RenameOpts.valueOf(opts_);
      return result == null ? ai.sapper.hcdc.common.model.DFSRenameFile.RenameOpts.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .ai_sapper_hcdc_common_model.DFSRenameFile.RenameOpts opts = 5;</code>
     */
    public Builder setOpts(ai.sapper.hcdc.common.model.DFSRenameFile.RenameOpts value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      opts_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .ai_sapper_hcdc_common_model.DFSRenameFile.RenameOpts opts = 5;</code>
     */
    public Builder clearOpts() {
      
      opts_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:ai_sapper_hcdc_common_model.DFSRenameFile)
  }

  // @@protoc_insertion_point(class_scope:ai_sapper_hcdc_common_model.DFSRenameFile)
  private static final ai.sapper.hcdc.common.model.DFSRenameFile DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ai.sapper.hcdc.common.model.DFSRenameFile();
  }

  public static ai.sapper.hcdc.common.model.DFSRenameFile getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DFSRenameFile>
      PARSER = new com.google.protobuf.AbstractParser<DFSRenameFile>() {
    public DFSRenameFile parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new DFSRenameFile(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DFSRenameFile> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DFSRenameFile> getParserForType() {
    return PARSER;
  }

  public ai.sapper.hcdc.common.model.DFSRenameFile getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

