// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_block.proto

package ai.sapper.hcdc.common.model;

/**
 * Protobuf type {@code ai_sapper_hcdc_common_model.DFSTransaction}
 */
public  final class DFSTransaction extends
    com.google.protobuf.GeneratedMessage
    implements DFSTransactionOrBuilder {
  // Use DFSTransaction.newBuilder() to construct.
  private DFSTransaction(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private DFSTransaction(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final DFSTransaction defaultInstance;
  public static DFSTransaction getDefaultInstance() {
    return defaultInstance;
  }

  public DFSTransaction getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private DFSTransaction(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            transactionId_ = input.readInt64();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();
            ai.sapper.hcdc.common.model.DFSTransaction.Operation value = ai.sapper.hcdc.common.model.DFSTransaction.Operation.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(2, rawValue);
            } else {
              bitField0_ |= 0x00000002;
              op_ = value;
            }
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            timestamp_ = input.readUInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ai.sapper.hcdc.common.model.DFSBlockProto.internal_static_ai_sapper_hcdc_common_model_DFSTransaction_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ai.sapper.hcdc.common.model.DFSBlockProto.internal_static_ai_sapper_hcdc_common_model_DFSTransaction_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ai.sapper.hcdc.common.model.DFSTransaction.class, ai.sapper.hcdc.common.model.DFSTransaction.Builder.class);
  }

  public static com.google.protobuf.Parser<DFSTransaction> PARSER =
      new com.google.protobuf.AbstractParser<DFSTransaction>() {
    public DFSTransaction parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DFSTransaction(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<DFSTransaction> getParserForType() {
    return PARSER;
  }

  /**
   * Protobuf enum {@code ai_sapper_hcdc_common_model.DFSTransaction.Operation}
   */
  public enum Operation
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ADD_FILE = 0;</code>
     */
    ADD_FILE(0, 0),
    /**
     * <code>ADD_BLOCK = 1;</code>
     */
    ADD_BLOCK(1, 1),
    /**
     * <code>CLOSE = 2;</code>
     */
    CLOSE(2, 2),
    /**
     * <code>RENAME = 3;</code>
     */
    RENAME(3, 3),
    /**
     * <code>CONCAT_DELETE = 4;</code>
     */
    CONCAT_DELETE(4, 4),
    /**
     * <code>UPDATE_BLOCKS = 5;</code>
     */
    UPDATE_BLOCKS(5, 5),
    /**
     * <code>DELETE = 6;</code>
     */
    DELETE(6, 6),
    /**
     * <code>APPEND = 7;</code>
     */
    APPEND(7, 7),
    /**
     * <code>TRUNCATE = 8;</code>
     */
    TRUNCATE(8, 8),
    /**
     * <code>IGNORE = 9;</code>
     */
    IGNORE(9, 9),
    ;

    /**
     * <code>ADD_FILE = 0;</code>
     */
    public static final int ADD_FILE_VALUE = 0;
    /**
     * <code>ADD_BLOCK = 1;</code>
     */
    public static final int ADD_BLOCK_VALUE = 1;
    /**
     * <code>CLOSE = 2;</code>
     */
    public static final int CLOSE_VALUE = 2;
    /**
     * <code>RENAME = 3;</code>
     */
    public static final int RENAME_VALUE = 3;
    /**
     * <code>CONCAT_DELETE = 4;</code>
     */
    public static final int CONCAT_DELETE_VALUE = 4;
    /**
     * <code>UPDATE_BLOCKS = 5;</code>
     */
    public static final int UPDATE_BLOCKS_VALUE = 5;
    /**
     * <code>DELETE = 6;</code>
     */
    public static final int DELETE_VALUE = 6;
    /**
     * <code>APPEND = 7;</code>
     */
    public static final int APPEND_VALUE = 7;
    /**
     * <code>TRUNCATE = 8;</code>
     */
    public static final int TRUNCATE_VALUE = 8;
    /**
     * <code>IGNORE = 9;</code>
     */
    public static final int IGNORE_VALUE = 9;


    public final int getNumber() { return value; }

    public static Operation valueOf(int value) {
      switch (value) {
        case 0: return ADD_FILE;
        case 1: return ADD_BLOCK;
        case 2: return CLOSE;
        case 3: return RENAME;
        case 4: return CONCAT_DELETE;
        case 5: return UPDATE_BLOCKS;
        case 6: return DELETE;
        case 7: return APPEND;
        case 8: return TRUNCATE;
        case 9: return IGNORE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Operation>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Operation>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Operation>() {
            public Operation findValueByNumber(int number) {
              return Operation.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ai.sapper.hcdc.common.model.DFSTransaction.getDescriptor().getEnumTypes().get(0);
    }

    private static final Operation[] VALUES = values();

    public static Operation valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Operation(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ai_sapper_hcdc_common_model.DFSTransaction.Operation)
  }

  private int bitField0_;
  // required int64 transactionId = 1;
  public static final int TRANSACTIONID_FIELD_NUMBER = 1;
  private long transactionId_;
  /**
   * <code>required int64 transactionId = 1;</code>
   */
  public boolean hasTransactionId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required int64 transactionId = 1;</code>
   */
  public long getTransactionId() {
    return transactionId_;
  }

  // required .ai_sapper_hcdc_common_model.DFSTransaction.Operation op = 2;
  public static final int OP_FIELD_NUMBER = 2;
  private ai.sapper.hcdc.common.model.DFSTransaction.Operation op_;
  /**
   * <code>required .ai_sapper_hcdc_common_model.DFSTransaction.Operation op = 2;</code>
   */
  public boolean hasOp() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required .ai_sapper_hcdc_common_model.DFSTransaction.Operation op = 2;</code>
   */
  public ai.sapper.hcdc.common.model.DFSTransaction.Operation getOp() {
    return op_;
  }

  // required uint64 timestamp = 3;
  public static final int TIMESTAMP_FIELD_NUMBER = 3;
  private long timestamp_;
  /**
   * <code>required uint64 timestamp = 3;</code>
   */
  public boolean hasTimestamp() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>required uint64 timestamp = 3;</code>
   */
  public long getTimestamp() {
    return timestamp_;
  }

  private void initFields() {
    transactionId_ = 0L;
    op_ = ai.sapper.hcdc.common.model.DFSTransaction.Operation.ADD_FILE;
    timestamp_ = 0L;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    if (!hasTransactionId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasOp()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasTimestamp()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt64(1, transactionId_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeEnum(2, op_.getNumber());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeUInt64(3, timestamp_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, transactionId_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, op_.getNumber());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, timestamp_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static ai.sapper.hcdc.common.model.DFSTransaction parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.sapper.hcdc.common.model.DFSTransaction parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.sapper.hcdc.common.model.DFSTransaction parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.sapper.hcdc.common.model.DFSTransaction parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.sapper.hcdc.common.model.DFSTransaction parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static ai.sapper.hcdc.common.model.DFSTransaction parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static ai.sapper.hcdc.common.model.DFSTransaction parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static ai.sapper.hcdc.common.model.DFSTransaction parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static ai.sapper.hcdc.common.model.DFSTransaction parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static ai.sapper.hcdc.common.model.DFSTransaction parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(ai.sapper.hcdc.common.model.DFSTransaction prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ai_sapper_hcdc_common_model.DFSTransaction}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements ai.sapper.hcdc.common.model.DFSTransactionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ai.sapper.hcdc.common.model.DFSBlockProto.internal_static_ai_sapper_hcdc_common_model_DFSTransaction_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ai.sapper.hcdc.common.model.DFSBlockProto.internal_static_ai_sapper_hcdc_common_model_DFSTransaction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ai.sapper.hcdc.common.model.DFSTransaction.class, ai.sapper.hcdc.common.model.DFSTransaction.Builder.class);
    }

    // Construct using ai.sapper.hcdc.common.model.DFSTransaction.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      transactionId_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      op_ = ai.sapper.hcdc.common.model.DFSTransaction.Operation.ADD_FILE;
      bitField0_ = (bitField0_ & ~0x00000002);
      timestamp_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ai.sapper.hcdc.common.model.DFSBlockProto.internal_static_ai_sapper_hcdc_common_model_DFSTransaction_descriptor;
    }

    public ai.sapper.hcdc.common.model.DFSTransaction getDefaultInstanceForType() {
      return ai.sapper.hcdc.common.model.DFSTransaction.getDefaultInstance();
    }

    public ai.sapper.hcdc.common.model.DFSTransaction build() {
      ai.sapper.hcdc.common.model.DFSTransaction result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public ai.sapper.hcdc.common.model.DFSTransaction buildPartial() {
      ai.sapper.hcdc.common.model.DFSTransaction result = new ai.sapper.hcdc.common.model.DFSTransaction(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.transactionId_ = transactionId_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.op_ = op_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.timestamp_ = timestamp_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ai.sapper.hcdc.common.model.DFSTransaction) {
        return mergeFrom((ai.sapper.hcdc.common.model.DFSTransaction)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ai.sapper.hcdc.common.model.DFSTransaction other) {
      if (other == ai.sapper.hcdc.common.model.DFSTransaction.getDefaultInstance()) return this;
      if (other.hasTransactionId()) {
        setTransactionId(other.getTransactionId());
      }
      if (other.hasOp()) {
        setOp(other.getOp());
      }
      if (other.hasTimestamp()) {
        setTimestamp(other.getTimestamp());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasTransactionId()) {
        
        return false;
      }
      if (!hasOp()) {
        
        return false;
      }
      if (!hasTimestamp()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ai.sapper.hcdc.common.model.DFSTransaction parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ai.sapper.hcdc.common.model.DFSTransaction) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // required int64 transactionId = 1;
    private long transactionId_ ;
    /**
     * <code>required int64 transactionId = 1;</code>
     */
    public boolean hasTransactionId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 transactionId = 1;</code>
     */
    public long getTransactionId() {
      return transactionId_;
    }
    /**
     * <code>required int64 transactionId = 1;</code>
     */
    public Builder setTransactionId(long value) {
      bitField0_ |= 0x00000001;
      transactionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 transactionId = 1;</code>
     */
    public Builder clearTransactionId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      transactionId_ = 0L;
      onChanged();
      return this;
    }

    // required .ai_sapper_hcdc_common_model.DFSTransaction.Operation op = 2;
    private ai.sapper.hcdc.common.model.DFSTransaction.Operation op_ = ai.sapper.hcdc.common.model.DFSTransaction.Operation.ADD_FILE;
    /**
     * <code>required .ai_sapper_hcdc_common_model.DFSTransaction.Operation op = 2;</code>
     */
    public boolean hasOp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .ai_sapper_hcdc_common_model.DFSTransaction.Operation op = 2;</code>
     */
    public ai.sapper.hcdc.common.model.DFSTransaction.Operation getOp() {
      return op_;
    }
    /**
     * <code>required .ai_sapper_hcdc_common_model.DFSTransaction.Operation op = 2;</code>
     */
    public Builder setOp(ai.sapper.hcdc.common.model.DFSTransaction.Operation value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      op_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required .ai_sapper_hcdc_common_model.DFSTransaction.Operation op = 2;</code>
     */
    public Builder clearOp() {
      bitField0_ = (bitField0_ & ~0x00000002);
      op_ = ai.sapper.hcdc.common.model.DFSTransaction.Operation.ADD_FILE;
      onChanged();
      return this;
    }

    // required uint64 timestamp = 3;
    private long timestamp_ ;
    /**
     * <code>required uint64 timestamp = 3;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint64 timestamp = 3;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>required uint64 timestamp = 3;</code>
     */
    public Builder setTimestamp(long value) {
      bitField0_ |= 0x00000004;
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required uint64 timestamp = 3;</code>
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000004);
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ai_sapper_hcdc_common_model.DFSTransaction)
  }

  static {
    defaultInstance = new DFSTransaction(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:ai_sapper_hcdc_common_model.DFSTransaction)
}

