// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package ai.sapper.common.model;

public final class CommonProto {
  private CommonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ai_sapper_common_model_BInteger_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ai_sapper_common_model_BInteger_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ai_sapper_common_model_BDecimal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ai_sapper_common_model_BDecimal_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\022\026ai_sapper_common_model\"\031" +
      "\n\010BInteger\022\r\n\005value\030\001 \002(\014\"]\n\010BDecimal\022\r\n" +
      "\005scale\030\001 \002(\005\022\021\n\tprecision\030\002 \002(\005\022/\n\005value" +
      "\030\003 \002(\0132 .ai_sapper_common_model.BInteger" +
      "B\'\n\026ai.sapper.common.modelB\013CommonProtoP" +
      "\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ai_sapper_common_model_BInteger_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ai_sapper_common_model_BInteger_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ai_sapper_common_model_BInteger_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_ai_sapper_common_model_BDecimal_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ai_sapper_common_model_BDecimal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ai_sapper_common_model_BDecimal_descriptor,
        new java.lang.String[] { "Scale", "Precision", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
