// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_block.proto

package ai.sapper.hcdc.common.model;

public interface DFSSchemaOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required string domain = 1;
  /**
   * <code>required string domain = 1;</code>
   */
  boolean hasDomain();
  /**
   * <code>required string domain = 1;</code>
   */
  java.lang.String getDomain();
  /**
   * <code>required string domain = 1;</code>
   */
  com.google.protobuf.ByteString
      getDomainBytes();

  // required string entity = 2;
  /**
   * <code>required string entity = 2;</code>
   */
  boolean hasEntity();
  /**
   * <code>required string entity = 2;</code>
   */
  java.lang.String getEntity();
  /**
   * <code>required string entity = 2;</code>
   */
  com.google.protobuf.ByteString
      getEntityBytes();

  // optional string group = 3;
  /**
   * <code>optional string group = 3;</code>
   */
  boolean hasGroup();
  /**
   * <code>optional string group = 3;</code>
   */
  java.lang.String getGroup();
  /**
   * <code>optional string group = 3;</code>
   */
  com.google.protobuf.ByteString
      getGroupBytes();
}
