// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_block.proto

package ai.sapper.cdc.common.model;

public interface DFSTransactionOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required int64 transactionId = 1;
  /**
   * <code>required int64 transactionId = 1;</code>
   */
  boolean hasTransactionId();
  /**
   * <code>required int64 transactionId = 1;</code>
   */
  long getTransactionId();

  // required .ai_sapper_hcdc_common_model.DFSTransaction.Operation op = 2;
  /**
   * <code>required .ai_sapper_hcdc_common_model.DFSTransaction.Operation op = 2;</code>
   */
  boolean hasOp();
  /**
   * <code>required .ai_sapper_hcdc_common_model.DFSTransaction.Operation op = 2;</code>
   */
  DFSTransaction.Operation getOp();

  // required uint64 timestamp = 3;
  /**
   * <code>required uint64 timestamp = 3;</code>
   */
  boolean hasTimestamp();
  /**
   * <code>required uint64 timestamp = 3;</code>
   */
  long getTimestamp();
}
