// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_block.proto

package ai.sapper.cdc.common.model;

/**
 * Protobuf type {@code ai_sapper_hcdc_common_model.DFSTruncateBlock}
 */
public  final class DFSTruncateBlock extends
    com.google.protobuf.GeneratedMessage
    implements DFSTruncateBlockOrBuilder {
  // Use DFSTruncateBlock.newBuilder() to construct.
  private DFSTruncateBlock(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private DFSTruncateBlock(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final DFSTruncateBlock defaultInstance;
  public static DFSTruncateBlock getDefaultInstance() {
    return defaultInstance;
  }

  public DFSTruncateBlock getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private DFSTruncateBlock(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            DFSTransaction.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
              subBuilder = transaction_.toBuilder();
            }
            transaction_ = input.readMessage(DFSTransaction.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(transaction_);
              transaction_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 18: {
            DFSFile.Builder subBuilder = null;
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
              subBuilder = file_.toBuilder();
            }
            file_ = input.readMessage(DFSFile.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(file_);
              file_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000002;
            break;
          }
          case 26: {
            DFSBlock.Builder subBuilder = null;
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
              subBuilder = block_.toBuilder();
            }
            block_ = input.readMessage(DFSBlock.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(block_);
              block_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000004;
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            newLength_ = input.readUInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return DFSBlockProto.internal_static_ai_sapper_hcdc_common_model_DFSTruncateBlock_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return DFSBlockProto.internal_static_ai_sapper_hcdc_common_model_DFSTruncateBlock_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            DFSTruncateBlock.class, DFSTruncateBlock.Builder.class);
  }

  public static com.google.protobuf.Parser<DFSTruncateBlock> PARSER =
      new com.google.protobuf.AbstractParser<DFSTruncateBlock>() {
    public DFSTruncateBlock parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DFSTruncateBlock(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<DFSTruncateBlock> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // required .ai_sapper_hcdc_common_model.DFSTransaction transaction = 1;
  public static final int TRANSACTION_FIELD_NUMBER = 1;
  private DFSTransaction transaction_;
  /**
   * <code>required .ai_sapper_hcdc_common_model.DFSTransaction transaction = 1;</code>
   */
  public boolean hasTransaction() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required .ai_sapper_hcdc_common_model.DFSTransaction transaction = 1;</code>
   */
  public DFSTransaction getTransaction() {
    return transaction_;
  }
  /**
   * <code>required .ai_sapper_hcdc_common_model.DFSTransaction transaction = 1;</code>
   */
  public DFSTransactionOrBuilder getTransactionOrBuilder() {
    return transaction_;
  }

  // required .ai_sapper_hcdc_common_model.DFSFile file = 2;
  public static final int FILE_FIELD_NUMBER = 2;
  private DFSFile file_;
  /**
   * <code>required .ai_sapper_hcdc_common_model.DFSFile file = 2;</code>
   */
  public boolean hasFile() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required .ai_sapper_hcdc_common_model.DFSFile file = 2;</code>
   */
  public DFSFile getFile() {
    return file_;
  }
  /**
   * <code>required .ai_sapper_hcdc_common_model.DFSFile file = 2;</code>
   */
  public DFSFileOrBuilder getFileOrBuilder() {
    return file_;
  }

  // required .ai_sapper_hcdc_common_model.DFSBlock block = 3;
  public static final int BLOCK_FIELD_NUMBER = 3;
  private DFSBlock block_;
  /**
   * <code>required .ai_sapper_hcdc_common_model.DFSBlock block = 3;</code>
   */
  public boolean hasBlock() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>required .ai_sapper_hcdc_common_model.DFSBlock block = 3;</code>
   */
  public DFSBlock getBlock() {
    return block_;
  }
  /**
   * <code>required .ai_sapper_hcdc_common_model.DFSBlock block = 3;</code>
   */
  public DFSBlockOrBuilder getBlockOrBuilder() {
    return block_;
  }

  // required uint64 newLength = 4;
  public static final int NEWLENGTH_FIELD_NUMBER = 4;
  private long newLength_;
  /**
   * <code>required uint64 newLength = 4;</code>
   */
  public boolean hasNewLength() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>required uint64 newLength = 4;</code>
   */
  public long getNewLength() {
    return newLength_;
  }

  private void initFields() {
    transaction_ = DFSTransaction.getDefaultInstance();
    file_ = DFSFile.getDefaultInstance();
    block_ = DFSBlock.getDefaultInstance();
    newLength_ = 0L;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    if (!hasTransaction()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasFile()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasBlock()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasNewLength()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getTransaction().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getFile().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getBlock().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeMessage(1, transaction_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeMessage(2, file_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeMessage(3, block_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeUInt64(4, newLength_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, transaction_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, file_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, block_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, newLength_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static DFSTruncateBlock parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DFSTruncateBlock parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DFSTruncateBlock parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DFSTruncateBlock parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DFSTruncateBlock parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static DFSTruncateBlock parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static DFSTruncateBlock parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static DFSTruncateBlock parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static DFSTruncateBlock parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static DFSTruncateBlock parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(DFSTruncateBlock prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ai_sapper_hcdc_common_model.DFSTruncateBlock}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements DFSTruncateBlockOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DFSBlockProto.internal_static_ai_sapper_hcdc_common_model_DFSTruncateBlock_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DFSBlockProto.internal_static_ai_sapper_hcdc_common_model_DFSTruncateBlock_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DFSTruncateBlock.class, DFSTruncateBlock.Builder.class);
    }

    // Construct using ai.sapper.hcdc.common.model.DFSTruncateBlock.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getTransactionFieldBuilder();
        getFileFieldBuilder();
        getBlockFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      if (transactionBuilder_ == null) {
        transaction_ = DFSTransaction.getDefaultInstance();
      } else {
        transactionBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (fileBuilder_ == null) {
        file_ = DFSFile.getDefaultInstance();
      } else {
        fileBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      if (blockBuilder_ == null) {
        block_ = DFSBlock.getDefaultInstance();
      } else {
        blockBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      newLength_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return DFSBlockProto.internal_static_ai_sapper_hcdc_common_model_DFSTruncateBlock_descriptor;
    }

    public DFSTruncateBlock getDefaultInstanceForType() {
      return DFSTruncateBlock.getDefaultInstance();
    }

    public DFSTruncateBlock build() {
      DFSTruncateBlock result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public DFSTruncateBlock buildPartial() {
      DFSTruncateBlock result = new DFSTruncateBlock(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      if (transactionBuilder_ == null) {
        result.transaction_ = transaction_;
      } else {
        result.transaction_ = transactionBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      if (fileBuilder_ == null) {
        result.file_ = file_;
      } else {
        result.file_ = fileBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      if (blockBuilder_ == null) {
        result.block_ = block_;
      } else {
        result.block_ = blockBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.newLength_ = newLength_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof DFSTruncateBlock) {
        return mergeFrom((DFSTruncateBlock)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(DFSTruncateBlock other) {
      if (other == DFSTruncateBlock.getDefaultInstance()) return this;
      if (other.hasTransaction()) {
        mergeTransaction(other.getTransaction());
      }
      if (other.hasFile()) {
        mergeFile(other.getFile());
      }
      if (other.hasBlock()) {
        mergeBlock(other.getBlock());
      }
      if (other.hasNewLength()) {
        setNewLength(other.getNewLength());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasTransaction()) {
        
        return false;
      }
      if (!hasFile()) {
        
        return false;
      }
      if (!hasBlock()) {
        
        return false;
      }
      if (!hasNewLength()) {
        
        return false;
      }
      if (!getTransaction().isInitialized()) {
        
        return false;
      }
      if (!getFile().isInitialized()) {
        
        return false;
      }
      if (!getBlock().isInitialized()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      DFSTruncateBlock parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (DFSTruncateBlock) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // required .ai_sapper_hcdc_common_model.DFSTransaction transaction = 1;
    private DFSTransaction transaction_ = DFSTransaction.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
            DFSTransaction, DFSTransaction.Builder, DFSTransactionOrBuilder> transactionBuilder_;
    /**
     * <code>required .ai_sapper_hcdc_common_model.DFSTransaction transaction = 1;</code>
     */
    public boolean hasTransaction() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .ai_sapper_hcdc_common_model.DFSTransaction transaction = 1;</code>
     */
    public DFSTransaction getTransaction() {
      if (transactionBuilder_ == null) {
        return transaction_;
      } else {
        return transactionBuilder_.getMessage();
      }
    }
    /**
     * <code>required .ai_sapper_hcdc_common_model.DFSTransaction transaction = 1;</code>
     */
    public Builder setTransaction(DFSTransaction value) {
      if (transactionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        transaction_ = value;
        onChanged();
      } else {
        transactionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .ai_sapper_hcdc_common_model.DFSTransaction transaction = 1;</code>
     */
    public Builder setTransaction(
        DFSTransaction.Builder builderForValue) {
      if (transactionBuilder_ == null) {
        transaction_ = builderForValue.build();
        onChanged();
      } else {
        transactionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .ai_sapper_hcdc_common_model.DFSTransaction transaction = 1;</code>
     */
    public Builder mergeTransaction(DFSTransaction value) {
      if (transactionBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            transaction_ != DFSTransaction.getDefaultInstance()) {
          transaction_ =
            DFSTransaction.newBuilder(transaction_).mergeFrom(value).buildPartial();
        } else {
          transaction_ = value;
        }
        onChanged();
      } else {
        transactionBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .ai_sapper_hcdc_common_model.DFSTransaction transaction = 1;</code>
     */
    public Builder clearTransaction() {
      if (transactionBuilder_ == null) {
        transaction_ = DFSTransaction.getDefaultInstance();
        onChanged();
      } else {
        transactionBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>required .ai_sapper_hcdc_common_model.DFSTransaction transaction = 1;</code>
     */
    public DFSTransaction.Builder getTransactionBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getTransactionFieldBuilder().getBuilder();
    }
    /**
     * <code>required .ai_sapper_hcdc_common_model.DFSTransaction transaction = 1;</code>
     */
    public DFSTransactionOrBuilder getTransactionOrBuilder() {
      if (transactionBuilder_ != null) {
        return transactionBuilder_.getMessageOrBuilder();
      } else {
        return transaction_;
      }
    }
    /**
     * <code>required .ai_sapper_hcdc_common_model.DFSTransaction transaction = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
            DFSTransaction, DFSTransaction.Builder, DFSTransactionOrBuilder>
        getTransactionFieldBuilder() {
      if (transactionBuilder_ == null) {
        transactionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                DFSTransaction, DFSTransaction.Builder, DFSTransactionOrBuilder>(
                transaction_,
                getParentForChildren(),
                isClean());
        transaction_ = null;
      }
      return transactionBuilder_;
    }

    // required .ai_sapper_hcdc_common_model.DFSFile file = 2;
    private DFSFile file_ = DFSFile.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
            DFSFile, DFSFile.Builder, DFSFileOrBuilder> fileBuilder_;
    /**
     * <code>required .ai_sapper_hcdc_common_model.DFSFile file = 2;</code>
     */
    public boolean hasFile() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .ai_sapper_hcdc_common_model.DFSFile file = 2;</code>
     */
    public DFSFile getFile() {
      if (fileBuilder_ == null) {
        return file_;
      } else {
        return fileBuilder_.getMessage();
      }
    }
    /**
     * <code>required .ai_sapper_hcdc_common_model.DFSFile file = 2;</code>
     */
    public Builder setFile(DFSFile value) {
      if (fileBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        file_ = value;
        onChanged();
      } else {
        fileBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>required .ai_sapper_hcdc_common_model.DFSFile file = 2;</code>
     */
    public Builder setFile(
        DFSFile.Builder builderForValue) {
      if (fileBuilder_ == null) {
        file_ = builderForValue.build();
        onChanged();
      } else {
        fileBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>required .ai_sapper_hcdc_common_model.DFSFile file = 2;</code>
     */
    public Builder mergeFile(DFSFile value) {
      if (fileBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            file_ != DFSFile.getDefaultInstance()) {
          file_ =
            DFSFile.newBuilder(file_).mergeFrom(value).buildPartial();
        } else {
          file_ = value;
        }
        onChanged();
      } else {
        fileBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>required .ai_sapper_hcdc_common_model.DFSFile file = 2;</code>
     */
    public Builder clearFile() {
      if (fileBuilder_ == null) {
        file_ = DFSFile.getDefaultInstance();
        onChanged();
      } else {
        fileBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    /**
     * <code>required .ai_sapper_hcdc_common_model.DFSFile file = 2;</code>
     */
    public DFSFile.Builder getFileBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getFileFieldBuilder().getBuilder();
    }
    /**
     * <code>required .ai_sapper_hcdc_common_model.DFSFile file = 2;</code>
     */
    public DFSFileOrBuilder getFileOrBuilder() {
      if (fileBuilder_ != null) {
        return fileBuilder_.getMessageOrBuilder();
      } else {
        return file_;
      }
    }
    /**
     * <code>required .ai_sapper_hcdc_common_model.DFSFile file = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
            DFSFile, DFSFile.Builder, DFSFileOrBuilder>
        getFileFieldBuilder() {
      if (fileBuilder_ == null) {
        fileBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                DFSFile, DFSFile.Builder, DFSFileOrBuilder>(
                file_,
                getParentForChildren(),
                isClean());
        file_ = null;
      }
      return fileBuilder_;
    }

    // required .ai_sapper_hcdc_common_model.DFSBlock block = 3;
    private DFSBlock block_ = DFSBlock.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
            DFSBlock, DFSBlock.Builder, DFSBlockOrBuilder> blockBuilder_;
    /**
     * <code>required .ai_sapper_hcdc_common_model.DFSBlock block = 3;</code>
     */
    public boolean hasBlock() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .ai_sapper_hcdc_common_model.DFSBlock block = 3;</code>
     */
    public DFSBlock getBlock() {
      if (blockBuilder_ == null) {
        return block_;
      } else {
        return blockBuilder_.getMessage();
      }
    }
    /**
     * <code>required .ai_sapper_hcdc_common_model.DFSBlock block = 3;</code>
     */
    public Builder setBlock(DFSBlock value) {
      if (blockBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        block_ = value;
        onChanged();
      } else {
        blockBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>required .ai_sapper_hcdc_common_model.DFSBlock block = 3;</code>
     */
    public Builder setBlock(
        DFSBlock.Builder builderForValue) {
      if (blockBuilder_ == null) {
        block_ = builderForValue.build();
        onChanged();
      } else {
        blockBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>required .ai_sapper_hcdc_common_model.DFSBlock block = 3;</code>
     */
    public Builder mergeBlock(DFSBlock value) {
      if (blockBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004) &&
            block_ != DFSBlock.getDefaultInstance()) {
          block_ =
            DFSBlock.newBuilder(block_).mergeFrom(value).buildPartial();
        } else {
          block_ = value;
        }
        onChanged();
      } else {
        blockBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>required .ai_sapper_hcdc_common_model.DFSBlock block = 3;</code>
     */
    public Builder clearBlock() {
      if (blockBuilder_ == null) {
        block_ = DFSBlock.getDefaultInstance();
        onChanged();
      } else {
        blockBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }
    /**
     * <code>required .ai_sapper_hcdc_common_model.DFSBlock block = 3;</code>
     */
    public DFSBlock.Builder getBlockBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getBlockFieldBuilder().getBuilder();
    }
    /**
     * <code>required .ai_sapper_hcdc_common_model.DFSBlock block = 3;</code>
     */
    public DFSBlockOrBuilder getBlockOrBuilder() {
      if (blockBuilder_ != null) {
        return blockBuilder_.getMessageOrBuilder();
      } else {
        return block_;
      }
    }
    /**
     * <code>required .ai_sapper_hcdc_common_model.DFSBlock block = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
            DFSBlock, DFSBlock.Builder, DFSBlockOrBuilder>
        getBlockFieldBuilder() {
      if (blockBuilder_ == null) {
        blockBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                DFSBlock, DFSBlock.Builder, DFSBlockOrBuilder>(
                block_,
                getParentForChildren(),
                isClean());
        block_ = null;
      }
      return blockBuilder_;
    }

    // required uint64 newLength = 4;
    private long newLength_ ;
    /**
     * <code>required uint64 newLength = 4;</code>
     */
    public boolean hasNewLength() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required uint64 newLength = 4;</code>
     */
    public long getNewLength() {
      return newLength_;
    }
    /**
     * <code>required uint64 newLength = 4;</code>
     */
    public Builder setNewLength(long value) {
      bitField0_ |= 0x00000008;
      newLength_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required uint64 newLength = 4;</code>
     */
    public Builder clearNewLength() {
      bitField0_ = (bitField0_ & ~0x00000008);
      newLength_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ai_sapper_hcdc_common_model.DFSTruncateBlock)
  }

  static {
    defaultInstance = new DFSTruncateBlock(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:ai_sapper_hcdc_common_model.DFSTruncateBlock)
}

